#This is the initial file for this project - Date: 6/27/25
import random

game_state = {
    "starting location" : "The Tavern", #Come up with a cool name later
    "current location" : None,
    "inventory" : ["Sword", "Shield", "2 Potion of Healing"],
    "health" : 100,
    "gold" : 15,
    "found_map" : False,
    "found_switch" : False,
}

dm_responses = {
    "action" : {

    }
}

global_actions = {
    "show inventory" : print(game_state["inventory"]),
    "show health" : print(game_state["health"]),
    "show gold" : print(game_state["gold"]),
    "show location" : print(game_state["current location"])
}

tavern_actions = {
    "look" : "The tavern is dimly lit, filled with the smell of ale and woodsmoke. A burly bartender polishes glasses behind the bar. In the corner, a hooded figure sits alone. Stairs lead up to the inn rooms to the right of the bar counter. Your trusty old traveling pack rests against your chair, worn from years of use. Various hunting trophies line the walls of the tavern, and a faded painting of a castle on the coastline hangs crooked near the door.",

    "talk to the bartender" : "The bartender sets down the glass he's been polishing and leans forward on the bar, eyeing you with interest. 'New face, eh? Haven't seen many travelers lately. Most folk are spooked by the old Moorwall Castle up on the cliffs - been abandoned for decades now.' He lowers his voice conspiratorially, 'Though between you and me, I've heard tell of treasures still hidden in those halls. Family heirlooms and such, left behind when the last lord fled. If you're feeling brave, just follow the north road out of town. Can't miss it - big imposing thing perched right on the cliff's edge. Just watch yourself... strange things been happening to those who venture too close after dark.'",

    "check the pack" : "You pull your trusty traveling pack closer and unfasten the worn leather straps. Inside, you find your usual supplies - some dried rations, a water flask, flint and steel, and 50 feet of rope. Tucked into the side pocket, your fingers brush against an old piece of parchment. Ah yes, your father's map - the one he pressed into your hands on his deathbed, marked with the location of your family's ancestral home. 'When the time is right,' he'd said, 'what was lost can be found again.' You've carried it for years, never quite finding the courage to follow its path. The map shows a castle on the cliffs, with annotations in your father's careful handwriting marking various entrances and... something else written in the old tongue.",

    "inspect the map" : "You carefully unfold the aged parchment, studying your father's meticulous work. The map shows Moorwall Castle perched on the eastern cliffs, with three distinct approaches marked in fading ink. The main road leads to the front gate - 'Where stone beasts keep watch' notes your father's hand. A winding path between the cliff rocks is marked with a small symbol of a rat - below it reads 'Cellar access - beware the dwellers.' The third route shows a side entrance through what appears to be a courtyard, marked with warnings: 'Guards patrol at dusk.' The most intriguing is a phrase written in the old tongue at the bottom of the map: 'Mor'thak vel'uun.' Your father taught you enough to know it means 'Shadow's bane.' Below that, in common script: 'Speak this at the heart, when darkness rises.' Whatever that means... The map is clearly old, but the castle's location is unmistakable - north of town, where the land meets the sea.",

    "go upstairs" : "You start toward the wooden stairs, but two red-faced patrons are completely blocking the way, deep in what might be the most ridiculous argument you've ever heard. 'The dice CLEARLY showed a one!' the shorter one insists. 'But it hit your tankard!' the taller one shoots back. 'That makes it a physics roll, not a dice roll! The universe decided!' 'THE UNIVERSE DOESN'T PLAY DICE!' 'THAT'S LITERALLY WHAT DICE ARE FOR!' The bartender catches your eye and shrugs apologetically. 'They've been at this for twenty minutes. Last week it was whether a chicken could be a familiar. I'm letting them tire themselves out.' A small crowd has gathered, taking bets on who'll win the argument. One particularly enterprising halfling is selling snacks. The stairs are completely inaccessible behind this philosophical dice disaster. Perhaps the inn rooms will have to wait for another time.",

    "leave" : "You stand up from your table, considering heading back out into the night. But something stops you at the threshold. You came to this tavern for a reason, didn't you? The weight of your father's map in your pack seems heavier suddenly, like it's been waiting long enough. The familiar fear creeps in - the same one that's kept you from following his cryptic directions all these years. Outside, the cool night air carries the salt tang of the sea cliffs. You could leave, go back to your routine, keep wondering 'what if.' Or... you could finally see what your father wanted you to find. The choice has always been yours. You're still standing in the tavern doorway. Will you truly leave, or is tonight the night you finally seek your inheritance?",

    "order a drink" : "You wave the bartender over and request an ale. 'Coming right up!' He pulls a well-worn tankard from beneath the bar and fills it with a rich, amber brew from a large cask. The foam settles perfectly at the rim. 'That'll be 2 gold pieces. This here's my special brew - Dragon's Breath Ale. Don't worry, it's just a name. Mostly.' He winks. As you take your first sip, warmth spreads through your chest. It's surprisingly smooth with a slight honey aftertaste and just a hint of... is that cinnamon? Whatever secret ingredients he uses, you feel reinvigorated. The aches from your travels seem to fade a bit. 'First one always hits the spot, doesn't it?' the bartender grins. 'Let me know if you need anything else. You look like you've got the weight of the world on your shoulders. Or at least a heavy decision.'",

    "inspect the trophies" : "You wander over to examine the hunting trophies adorning the walls. There's an impressive variety - a massive boar's head with tusks like curved daggers, several mounted antlers from various deer, and what appears to be a stuffed badger locked in an eternal snarl. Pride of place goes to an enormous bear's head above the fireplace, its glass eyes seeming to follow patrons around the room. A small brass plaque beneath the bear reads: 'Killed by Hrolf the Bartender, Year of the Crimson Moon.' You glance back at the portly, balding bartender and try to imagine it. He catches your look and flexes one arm with a grin. 'I was younger then!'",

    "inspect the painting" : "You walk closer to the faded painting by the door, straightening it on its nail. The artist captured Moorwall Castle in what must have been its glory days - proud towers reaching skyward, pennants snapping in the coastal wind. The detail is remarkable despite the age. You can make out three distinct features: the main gatehouse facing the road, sturdy and imposing; the eastern wall where it meets the cliff face, with small cave openings visible in the rocks below; and oddly, a section of the western wall that appears to have been painted over, then sketched again with slightly different stonework. Squinting closer at that western section, you notice what might be a garden or courtyard, with tiny figures that could be patrols or... gardeners? It's hard to tell. But there's something deliberate about how the artist revised that area, like they were correcting a secret that shouldn't have been revealed. At the bottom corner, barely visible, is the artist's signature: 'R. Moorwall.' A family member, perhaps? Someone who knew the castle's secrets?",

    "approach hooded figure" : "You push back your chair and start walking toward the hooded figure in the corner. As your footsteps echo across the tavern floor, you notice their gloved hand tighten almost imperceptibly around their tankard. When you're halfway across the room, the figure suddenly stands in one fluid motion, keeping their face hidden in the depths of their hood. Before you can speak, they glide past you with unnatural grace, smelling faintly of rain and something else... something acrid, like old magic. You turn to follow, but in the brief moment it took to navigate around a drunk patron, they've vanished. The tavern door hasn't moved. The stairs remain blocked. Yet the corner where they sat is empty, only a full, untouched mug of ale proving they were ever there at all. The bartender, if he noticed anything, seems very focused on polishing that same glass. The other patrons continue their conversations as if nothing happened. But you know what you saw. Whoever that was, they definitely didn't want to chat."
}

# Transition scene to front gate of castle
no_map_front_transition = "You finish your ale, leaving a few coins on the scarred wooden table. The bartender gives you a knowing nod as you adjust your pack and head for the door. 'Good luck out there,' he calls. 'Remember - follow the north road. Can't miss it.' The cool night air hits you as you step outside, carrying the salt tang of the distant sea. The cobblestone streets of town quickly give way to a dirt road leading north, just as the bartender described. As you walk, the sounds of the tavern fade behind you, replaced by the whisper of wind through tall grass and the distant crash of waves against cliffs. After about an hour's trek, the road begins to climb. The moon breaks through the clouds, and there it is - Moorwall Castle, perched on the cliff's edge like a great stone bird of prey. Even in its abandoned state, it's imposing. Dark windows stare down at you like hollow eyes. You follow the road right up to the main gate - a massive wooden door reinforced with rusted iron bands. Heavy chains and an ancient padlock bar your way. But something feels off... the dust around the gate has been disturbed recently. You're not the first person to come here."

map_found_front_transition = "You finish your ale, leaving a few coins on the scarred wooden table. The bartender gives you a knowing nod as you adjust your pack and head for the door. 'Good luck out there,' he calls. 'Remember - follow the north road. Can't miss it.' The cool night air hits you as you step outside, carrying the salt tang of the distant sea. The cobblestone streets of town quickly give way to a dirt road leading north, just as the bartender described. As you walk, the sounds of the tavern fade behind you, replaced by the whisper of wind through tall grass and the distant crash of waves against cliffs. After about an hour's trek, the road begins to climb. The moon breaks through the clouds, and there it is - Moorwall Castle, perched on the cliff's edge like a great stone bird of prey. Even in its abandoned state, it's imposing. Dark windows stare down at you like hollow eyes. You follow the road right up to the main gate - a massive wooden door reinforced with rusted iron bands. It's exactly as your father's map described: 'Sealed by order of the Lord.' Indeed, heavy chains and an ancient padlock bar your way. But something feels off... the dust around the gate has been disturbed recently. You're not the first person to come here. Time to find that hidden switch the map mentioned. But where would someone hide such a mechanism?"

castle_front_actions = {
    "look around" : "You stand before the imposing front gate of Moorwall Castle. The ancient wooden doors tower above you, easily twice your height, reinforced with thick iron bands that have rusted to a deep brown. Heavy chains thread through the handles, secured with a massive padlock bearing the Moorwall seal. The stone walls rise up on either side, weathered but solid after all these years. To your left, an old iron torch sconce juts from the wall at an odd angle, like it's barely clinging to its mounting. To your right, a pair of stone gargoyles perch above the gate, their grotesque faces frozen in eternal grimaces. Even in the moonlight, you can make out the detail in their carved features - whoever sculpted them took pride in every scale and fang. The ground near the gate shows signs of recent disturbance - scuff marks in the dirt, handprints on dusty stone where someone felt along the walls. Your mysterious predecessor seemed to have searched thoroughly before giving up. Behind you, the road winds back down toward town. Ahead, the castle waits, silent and forbidding. Somewhere beyond these gates lies your inheritance... if you can figure out how to get inside.",

    "inspect wall" : "You run your hands along the cold stone walls, searching for any weakness or secret. The masonry is masterful - each stone fitted so perfectly you couldn't slip a blade between them. The wall stretches up at least twenty feet, topped with weathered battlements that still look wickedly defensive. For a moment, you consider climbing. There are enough gaps and weathered spots that could serve as handholds. You test one, pulling yourself up a few feet and... The moment you rise above the height of the gate, a sudden chill shoots through your body. Your fingers go numb, your vision blurs, and an overwhelming sense of wrongness floods your mind. You drop back to the ground, gaspig. The sensation vanishes immediately. A ward. Of course. The Moorwalls weren't fools - why build higher walls when magic does the job better? The protection extends upward and, you suspect, probably prevents tunneling under as well. Whatever's in this castle, someone wanted it to stay there... or keep others out. No wonder your predecessor's footprints led away. This isn't a problem you can solve with a rope and determination.",

    "pull chains" : "You grip the heavy chains in both hands and pull with all your might. They rattle impressively, sending echoes through the courtyard, but don't budge an inch. You try different angles - yanking sideways, upward, even planting your foot on the door for leverage. Nothing. The padlock is absolutely massive, its keyhole large enough to fit your thumb. Testing the chains link by link, you find them solid despite their apparent age. The lock itself shows interesting wear patterns though - scratches around the keyhole that look fresh, not decades old. Someone definitely tried picking this recently. Looking closer at the chains, you notice something odd. While rust covers most of the metal, there are spots where it's been rubbed away - handprints where someone else gripped these same links, probably within the last few days. The dust beneath the lock has been disturbed too, and you spot what might be the tip of a broken lockpick wedged in the mechanism. Your predecessor was determined, you'll give them that. But all their effort couldn't crack this seal. The Moorwalls built this to last, and no amount of brute force or lockpicking skill is going to change that. There has to be another way - one that doesn't involve wrestling with chains that have resisted who knows how many treasure seekers before you",

    "leave" : "You take a few steps back from the gate, frustration building in your chest. For a moment, you consider the long walk back to town - a warm bed at the inn sounds pretty good right now. But as you turn away, something stops you. The years of wondering. The fact that someone else is clearly after the same thing you are. No, you've come too far to give up at the first locked door. You find yourself walking back to the gate, studying it with fresh eyes. Your inheritance is somewhere behind these walls, and you'll be damned if you're leaving without at least trying everything. There has to be a way in. You just need to think differently. The gate looms before you once again, waiting.",

    "inspect torch" : "You examine the old iron torch sconce protruding from the wall. It's definitely seen better days - the metal is pitted with rust and the whole fixture hangs at an awkward angle, tilting downward like it's given up on its job. The mounting appears loose where it connects to the stone. Running your fingers along the sconce, you feel years of accumulated grime and weather. It's empty of course - no torch has burned here in decades. The iron is cold to the touch and slightly rough with corrosion. As you test its stability, the whole thing shifts slightly, grating against the stone with a grinding sound that makes you wince. Curiously, despite its drooping angle, the sconce seems... sturdy? Like it's hanging that way on purpose rather than from decay. The bottom portion disappears into a decorated metal housing where it meets the wall - probably meant to catch dripping pitch back in its working days. Hard to see much detail in this light though.",

    "inspect gargoyles" : "You approach the stone gargoyles perched above the gate, craning your neck to get a better look. There are two of them, mirror images flanking either side, their grotesque faces frozen in eternal grimaces. The craftsmanship is remarkable - every scale, fang, and claw rendered in meticulous detail despite decades of weather. Their expressions are fierce, meant to ward off evil spirits or unwelcome visitors. Bulging eyes, flared nostrils, tongues lolling between sharp teeth. But what strikes you most is their eyes - while their faces snarl down at approaching visitors, both sets of stone eyes are turned sharply to the left, focused intently on the same fixed point along the wall. You run your hands along their bases, checking for hidden mechanisms or loose stones. Nothing. They're solid sculpture through and through, purely decorative as far as you can tell. Still, there's something unsettling about those turned eyes, like they're trying to draw your attention to something. The sculptor clearly positioned them this way on purpose. Whatever secret this gate holds, the gargoyles themselves aren't it. But their stone gaze seems almost insistent, if centuries-old carvings could have such intentions.",

    "press switch" : "You crouch down and examine the bottom of the torch sconce more carefully this time. That decorated metal housing where it meets the wall... Running your fingers along its edge, you feel an unusual seam. With growing excitement, you grip the iron fixture and give it an experimental twist. It turns. The entire bottom piece rotates a quarter turn to the left with a satisfying click, revealing what was hidden beneath - a small stone button, cunningly concealed within the mechanism. Your heart races. This is it. This is what your father knew about, what your predecessor missed in their frantic searching. You press the button. For a moment, nothing happens. Then, a deep grinding sound echoes from within the gate mechanism. Ancient gears, untouched for decades, groan to life. The massive chains begin to slacken, sliding through the handles with a rattling crash. The padlock falls away - it was never truly locked, just part of the illusion. With a tremendous creaking that probably wakes half the countryside, the great doors of Moorwall Castle swing slowly inward, revealing a darkened courtyard beyond. After all these years, the way is finally open. Your inheritance awaits."
}

# Transition scene to castle cellar
no_map_cellar_transition = "You decide to trust the patron's whispered advice about a 'secret way through the cliffs.' Following their vague directions, you leave the tavern and head east toward where the land meets the sea. The main road would take you to the castle's front gate, but you're after something more discrete. The path grows rougher as you leave town, eventually becoming little more than a goat track winding between weather-worn boulders. The sound of waves crashing against rocks grows louder. After nearly an hour of careful climbing and more than one wrong turn, you finally spot what the patron described - a narrow path leading down the cliff face. Your stomach drops as you peer over the edge. The 'path' is generous - it's more like a series of ledges and handholds carved by time and desperate travelers. Far below, waves surge against jagged rocks. But there, about halfway down, you can make out what looks like cave openings in the cliff face.Taking a deep breath, you begin your descent. Every foothold sends loose pebbles tumbling into the darkness below. By the time you reach the cave entrance, your arms are shaking and your clothes are damp with sea spray. The opening is larger than it looked from above - easily tall enough to walk through. The air smells of salt, mold, and something else... something animal. From deep within, you hear the sound the patron warned you about - chittering and squeaking. Rats. Of course it's rats. Nothing's ever easy, is it?"

map_found_cellar_transition = "Your father's map clearly marks the cellar entrance - a path between the cliff rocks with a small rat symbol and the warning 'beware the dwellers.' At least you know exactly what you're walking into. Following the detailed directions, you leave the tavern and head east with purpose. The map leads you along an old smuggler's route your father apparently knew well. Hidden markers carved into rocks guide you - a crescent here, an arrow there. In half the time it would take a casual searcher, you find the concealed path down the cliff face. It's still treacherous, but your father's annotations help. 'Third ledge loose - test first.' 'Rope anchor point here.' 'Cave entrance behind the fallen boulder.' His guidance turns a dangerous climb into merely a challenging one. You can almost feel his presence, teaching you the way. Reaching the cave mouth, you pause to check the map one more time. Your father's notes are specific: 'Rat colony in main tunnel. They fear fire but grow bold in complete darkness. Old Moorwall wine cellar lies beyond - servants used this during siege of 1247.' From within comes the chittering the map promised. At least you're prepared. Your father even noted 'stay left at the first fork - right tunnel collapsed.' The man thought of everything. Time to see if his knowledge extends to what treasures - or dangers - await in the castle proper."

castle_cellar_actions = {}
castle_courtyard_actions = {}
castle_interior_actions = {}
final_confrontation_actions = {}

# Transition Actions
cliff_path_actions = {}
castle_gate_actions = {}

